version: "3.1" # docker-composeのバージョン指定
services:
  # コンテナの設定.
  my-mysql:
    # コンテナ名
    image: mysql:8.0 # イメージ名とは、コンテナの元となるファイルシステムのこと
    command: --default-authentication-plugin=mysql_native_password # 認証プラグインの設定とは、MySQL8.0からデフォルトでcaching_sha2_passwordになっているので、mysql_native_passwordに変更する必要がある
    container_name: my-mysql # コンテナ名
    volumes:
      # ボリュームの設定とは、コンテナ内のデータをホスト側に永続化するための設定
      # 永続化用のマウント先とは、コンテナ内のデータをホスト側に永続化するための設定
      # - ./sql/data:/var/lib/mysql
      # my.cnfの設定とは、MySQLの設定ファイルをコンテナ内にマウントする
      - ./sql/myconf/my.cnf:/etc/mysql/conf.d/my.cnf # 初期データとは、コンテナ起動時に実行するSQLファイルを指定する
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    environment:
      # 環境変数の設定とは、コンテナ内で使用する環境変数を設定する
      MYSQL_DATABASE: invoice_db
      MYSQL_USER: user # ユーザー名
      MYSQL_PASSWORD: password # パスワード
      MYSQL_ROOT_PASSWORD: pass # rootパスワードとは、MySQLのrootユーザーのパスワードを設定する
    ports:
      # ポートの設定とは、コンテナ内のポートをホスト側に公開するための設定
      - "3306:3306" # ホスト側のポート:コンテナ側のポート
